dashboardRoute:
  host: traefik.{{ .Values.ingressDomain }}
#  path: /admin/ingress

traefik:
  {{- if .Values.registry }}
  image: 
    name: {{ .Values.registry }}/traefik
  {{- end }}
  ingressClass:
    fallbackApiVersion: "v1"

  service:
    enabled: true
    type: LoadBalancer
{{- if .Values.ingress }}
  {{- if .Values.ingress.loadbalancerResourceGroup }}
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.ingress.loadbalancerResourceGroup | quote }}
  {{- end }}
{{- end }}
{{- if .Values.ingress }}
  {{- if .Values.ingress.loadBalancerIP }}
    spec:
      loadBalancerIP: {{ .Values.ingress.loadBalancerIP }}
#      selector:
#        app: azure-load-balancer
  {{- end }}
{{- end }}

  ports:
{{- if .Values.ingress.webPort }}
    web:
      exposedPort: {{ .Values.ingress.webPort }}
{{- end}}
    websecure:
{{- if .Values.ingress.websecurePort }}
      exposedPort: {{ .Values.ingress.websecurePort }}
{{- end}}
      tls: 
        enabled: true

  logs:
    access:
      enabled: true

  providers:
    kubernetesCRD:
      allowCrossNamespace: true
