dashboardRoute:
  host: ingress.{{ .Values.ingress.domain }}

traefik:
  image:
    {{- if .Values.registry }}
    name: {{ .Values.registry }}/traefik
    {{- end }}
    tag: "v2.5.3"
    pullPolicy: "Always"
  ingressClass:
    fallbackApiVersion: "v1"
  service:
    enabled: true
    type: LoadBalancer
<<<<<<< HEAD:yggdrasil/services/networking/ingress.yaml
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.ingress.loadbalancerResourceGroup  }}
    spec:
      loadBalancerIP: {{ .Values.ingress.loadBalancerIP }}
      selector:
        app: azure-load-balancer

  ports:
    websecure:
      tls:
=======
{{- if .Values.ingress.loadbalancerResourceGroup }}
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.ingress.loadbalancerResourceGroup | quote }}
{{- end }}
    spec: 
      loadBalancerIP: {{ .Values.ingress.loadBalancerIP }}

  ports:
    websecure:
      tls: 
>>>>>>> a881991c3b922a5e4040cb320e3216c2d13a6fad:yggdrasil/services/networking/ingress/ingress.yaml
        enabled: true  

  logs:
    access:
      enabled: true
