name: eo-postgresql
namespace: eo-postgresql
description: EnergyOrigin


project:
  name: eo-postgresql
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  destinations: 
    - namespace: kube-system
      server: https://kubernetes.default.svc
apps:
  - name: eo-postgresql
    source:
      repoURL: "https://github.com/bitnami/charts.git"
      targetRevision: master
      path: bitnami/postgresql
      valuesFile: "eo-postgresql.yaml"
