name: monitoring
clusterService: true
namespace: monitoring
description: All the monitoring apps, including but not limited to prometheus, grafana, thanos, loki. 

project:
  name: monitoring
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  destinations: 
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: rook-ceph
      server: https://kubernetes.default.svc
    
apps:
  - name: prometheus
    source:
      repoURL: 'https://github.com/distributed-technologies/prometheus.git'
      targetRevision: development
      path: chart
      valuesFile: "prometheus.yaml"
    ingressAnnotation:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    ingress:
      prometheus:
        subDomain: prometheus
        path: /
        servicePort: 9090
        serviceName: prometheus-kube-prometheus-prometheus
  - name: thanos
    source:
      repoURL: 'https://github.com/Open-Olympus-Project/tooling-thanos.git'
      # standard targetRevision is HEAD
      targetRevision: dependency
      # path to Helm chart in repo. Should be . if Helm chart is in root. 
      path: thanos
      # filename of values file that is local right next to this config.yaml file
      valuesFile: "thanos.yaml"
  - name: grafana
    source:
      repoURL: 'https://github.com/Open-Olympus-Project/tooling-grafana.git'
      # standard targetRevision is HEAD
      targetRevision: dependency
      # path to Helm chart in repo. Should be . if Helm chart is in root. 
      path: grafana
      # filename of values file that is local right next to this config.yaml file
      valuesFile: "grafana.yaml"
    ingressAnnotation:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    ingress:
      grafana:  
        subDomain: grafana
        path: /
        servicePort: 80
        serviceName: grafana
  - name: loki
    source:
      repoURL: 'https://github.com/Open-Olympus-Project/tooling-loki.git'
      # standard targetRevision is HEAD
      targetRevision: dependency
      # path to Helm chart in repo. Should be . if Helm chart is in root. 
      path: loki
      # filename of values file that is local right next to this config.yaml file
      valuesFile: "loki.yaml"
    ingressAnnotation:
      traefik.ingress.kubernetes.io/router.entrypoints: web
    ingress:
      prometheus:
        subDomain: loki
        path: /
        servicePort: 3100
        serviceName: loki
  - name: jaeger-operator
    source:
      repoURL: 'https://github.com/Open-Olympus-Project/tooling-jaeger-operator.git'
      # standard targetRevision is HEAD
      targetRevision: dependency
      # path to Helm chart in repo. Should be . if Helm chart is in root. 
      path: jaeger-operator
      # filename of values file that is local right next to this config.yaml file
      valuesFile: "jaeger-operator.yaml"
