kube-prometheus-stack:
  grafana:
    enabled: false
  {{- if .Values.registry -}}
  alertmanager: 
    alertmanagerSpec:
      image: 
        repository: {{ .Values.repository }}/prometheus/alertmanager
  prometheusOperator:
    admissionWebhooks: 
      patch:
        image: 
          repository: {{ .Values.repository }}/jettech/kube-webhook-certgen
    image: 
      repository: {{ .Values.repository }}/prometheus-operator/prometheus-operator 
    prometheusConfigReloaderImage: 
      repository: {{ .Values.repository }}/prometheus-operator/prometheus-config-reloader
  {{- end -}}

  prometheus: 
    prometheusSpec: 
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: prometheus
      replicas: 3
  {{- if .Values.registry -}}
      image: 
        repository: {{ .Values.repository }}/prometheus/prometheus

  kube-state-metrics: 
    image:
      repository: {{ .Values.repository }}/kube-state-metrics/kube-state-metrics

  prometheus-node-exporter:
    image:
      repository: {{ .Values.repository }}/prometheus/node-exporter
  {{- end -}}
