kube-prometheus-stack:
  grafana:
    enabled: false
  alertmanager: 
    alertmanagerSpec:
      image: 
        repository: harbor.sc.garagen/yggdrasil/quay.io/prometheus/alertmanager
        tag: v0.22.0
  prometheusOperator:
    admissionWebhooks: 
      patch:
        image: 
          repository: harbor.sc.garagen/yggdrasil/jettech/kube-webhook-certgen
          tag: v1.5.2
    image: 
      repository: harbor.sc.garagen/yggdrasil/quay.io/prometheus-operator/prometheus-operator 
      tag: v0.48.0
  prometheusConfigReloaderImage: 
    repository: harbor.sc.garagen/yggdrasil/quay.io/prometheus-operator/prometheus-config-reloader
    tag: v0.48.0
  prometheus: 
    prometheusSpec: 
      image: 
        repository: harbor.sc.garagen/yggdrasil/quay.io/prometheus/prometheus
        tag: v2.27.1
