name: nifi
clusterService: true
namespace: nifi
description: Nifi.

project:
  name: nifi
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  destinations:
    - namespace: kafka
      server: https://kubernetes.default.svc  

apps:
  - name: nifi
    replace: true
    source:
      repoURL: "https://github.com/cetic/helm-nifi.git"
      targetRevision: HEAD
      path: "."
      valuesFile: "nifi.yaml"
