name: networking
namespace: networking
namespaceLabels:
  space: service
space: service
description: networking services like ingress, cert-manager.

apps:
  - name: ingress
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.2.4
      chart: traefik
      valuesFile: "ingress.yaml"
  - name: cert-manager
    source:
      repoURL: "https://github.com/distributed-technologies/service-cert-manager.git"
      targetRevision: 0.1.0
      path: chart
      valuesFile: "cert-manager.yaml"
