name: networking
clusterService: true
namespace: networking
description: networking services like ingress, cert-manager.


project:
  name: networking
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  destinations: 
    - namespace: kube-system
      server: https://kubernetes.default.svc
apps:
  - name: ingress
    source:
      repoURL: "https://github.com/distributed-technologies/services-ingress.git"
      targetRevision: HEAD
      path: chart
      valuesFile: "ingress.yaml"
  - name: cert-manager
    source:
      repoURL: "https://github.com/Open-Olympus-Project/k8s-certmanager.git"
      targetRevision: dependency
      path: cert-manager
      valuesFile: "cert-manager.yaml"
  - name: cert-manager-issuer
    source:
      repoURL: "https://github.com/Open-Olympus-Project/k8s-certmanager.git"
      targetRevision: dependency
      path: cert-manager-issuer
      valuesFile: "cert-manager-issuer.yaml"