dashboardRoute:
  host: ingress.{{ .Values.ingressDomain }}

traefik:
  image:
    {{- if .Values.registry }}
    name: {{ .Values.registry }}/traefik
    {{- end }}
    tag: "v2.5.3"
    pullPolicy: "Always"
  ingressClass:
    fallbackApiVersion: "v1"
  service:
    enabled: true
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: rg-eo-P-001
    spec:
      loadBalancerIP: 20.101.225.251
      selector:
        app: azure-load-balancer

  ports:
    websecure:
      tls:
        enabled: true  

  logs:
    access:
      enabled: true
