# serviceDomain: {{ .Values.fqdn }}

dashboardRoute:
  host: ingress.{{ .Values.ingressDomain }}

traefik:
  ingressClass:
    fallbackApiVersion: "v1"

  service:
    enabled: true
    type: LoadBalancer
    # type: NodePort
    spec: 
      loadBalancerIP: 192.168.1.49

  # ports:
  #   web:
  #     nodePort: 32080
  #   websecure:
  #     nodePort: 32443
