

dashboardRoute:
  host: ingress.{{ .Values.ingressDomain }}

traefik:
  image: 
    name: harbor.sc.garagen/yggdrasil/traefik
    tag: "v2.4.7"
  ingressClass:
    fallbackApiVersion: "v1"

  service:
    enabled: true
    type: LoadBalancer
#    type: NodePort
    spec: {}
#      loadBalancerIP: 172.18.0.19

#  ports:
#    web:
#      nodePort: 32080
#    websecure:
#      nodePort: 32443
#      tls: 
#        enabled: true  

  logs:
    access:
      enabled: true
