dashboardRoute:
  host: ingress.{{ .Values.ingressDomain }}

traefik:
  image:
    {{- if .Values.registry }}
    name: {{ .Values.registry }}/traefik
    {{- end }}
    tag: "v2.5.3"
    pullPolicy: "Always"
  ingressClass:
    fallbackApiVersion: "v1"

  service:
    enabled: true
    type: LoadBalancer

  ports:
    websecure:
      tls:
        enabled: true  

  logs:
    access:
      enabled: true
