name: tooling
clusterService: true
namespace: tooling
description: Tooling services Argo WF, Harbor.

project:
  name: tooling
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: argowf
    source:
      repoURL: "https://github.com/distributed-technologies/services-argowf.git"
      targetRevision: argowf-dependency
      path: chart
      valuesFile: "argowf.yaml"
    ingress:
      - subDomain: argowf
        path: /
        servicePort: 2746
        serviceName: argowf-server 
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: web
  - name: argo-events
    source:
      repoURL: "https://github.com/Open-Olympus-Project/tooling-argo-events.git"
      targetRevision: dependency
      path: argo-events
      valuesFile: "argo-events.yaml"
    ingress:
      - subDomain: harbor
        path: /
        servicePort: 80
        serviceName: harbor-harbor-portal
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
      - subDomain: harbor
        path: /api
        servicePort: 80
        serviceName: harbor-harbor-core
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
      - subDomain: harbor
        path: /service
        servicePort: 80
        serviceName: harbor-harbor-core
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
      - subDomain: harbor
        path: /v2
        servicePort: 80
        serviceName: harbor-harbor-core
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
      - subDomain: harbor
        path: /c
        servicePort: 80
        serviceName: harbor-harbor-core
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
  - name: vault
    source:
      repoURL: "https://github.com/Open-Olympus-Project/tooling-vault.git"
      targetRevision: dependency
      path: vault
      valuesFile: "vault.yaml"
