name: tooling
namespace: tooling
namespaceLabels:
  space: service
space: service
description: Tooling services Argo WF, Harbor.

apps:
  - name: argowf
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.3
      path: charts/argo-wf/chart
      valuesFile: "argowf.yaml"
    ingress:
      - subDomain: argowf
        path: /
        servicePort: 2746
        serviceName: argowf-server 
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: web
  - name: argo-events
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.4
      path: charts/argo-events/chart
      valuesFile: "argo-events.yaml"
  - name: harbor
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.3
      path: charts/harbor/chart
      valuesFile: "harbor.yaml"
    ingress:
      - subDomain: harbor
        path: /
        servicePort: 80
        serviceName: harbor-harbor-portal
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
      - subDomain: harbor
        path: /api
        servicePort: 80
        serviceName: harbor-harbor-core
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
      - subDomain: harbor
        path: /service
        servicePort: 80
        serviceName: harbor-harbor-core
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
      - subDomain: harbor
        path: /v2
        servicePort: 80
        serviceName: harbor-harbor-core
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
      - subDomain: harbor
        path: /c
        servicePort: 80
        serviceName: harbor-harbor-core
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: "web, websecure"
  - name: vault
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.1
      path: charts/vault/chart
      valuesFile: "vault.yaml"
