name: azure-func-demo
clusterService: false
namespace: azure-func-demo
description: azure function demo.

project:
  name: azure-func-demo
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*' 

apps:
  - name: azure-func-demo
    source:
      repoURL: "https://github.com/distributed-technologies/azure-function-demo.git"
      targetRevision: HEAD
      path: chart
      valuesFile: "azure-func-demo.yaml"
    # ingress:
    #   - subDomain: azure-func-demo
    #       path: /
    #       servicePort: 80
    #       serviceName: azure-func-demo
    #       annotation:
    #       traefik.ingress.kubernetes.io/router.entrypoints: web
  