apiVersion: v2
type: application
name: yggdrasil
description: A Helm chart for for deploying an entire repo.
version: v0.4.8

dependencies: 
  - name: lightvessel
    version: "v0.1.1"
    repository: "https://distributed-technologies.github.io/helm-repository/"
