# This values is if you want to use paths instead of subdomains.
ingressDomain: ingress.lynderup.net

networking:
  enabled: true

  ingress:
    enabled: true

  cert-manager:
    enabled: true

  cert-manager-issuer: 
    enabled: true

tooling: 
  enabled: true

  argowf:
    enabled: false

  argo-events:
    enabled: false

  harbor:
    enabled: false

  vault:
    enabled: false

  trow: 
    enabled: true

monitoring:
  enabled: false

  prometheus:
    enabled: false

  thanos:
    enabled: false
  
  grafana:
    enabled: false
  
  loki:
    enabled: false

  jaeger-operator:
    enabled: false

rook-ceph: 
  enabled: true

  rook:
    enabled: true

  ceph: 
    enabled: true

loadbalancer: 
  enabled: false

  loadbalancer: 
    enabled: false

cache: 
  enabled: faæse
  
  cache:
    enabled: false

kafka: 
  enabled: false

  kafka: 
    enabled: false

# The same name as the project - This can be used to disable the whole project and namespace.
example-guestbook:
  enabled: false

  # The same name as one of the apps listed under the project.
  example-guestbook:
    enabled: false
