# This values is if you want to use paths instead of subdomains.
ingressDomain: dev2.eloprindelse.dk


applications: 
 - ingress
#  - cert-manager
#  - cert-manager-issuer 
#  - argowf
#  - argo-events
#  - harbor
#  - vault
 - prometheus
 - thanos
 - grafana
 - loki
 - jaeger-operator
#  - rook
#  - ceph
#  - loadbalancer
#  - cache
 - kafka
#  - nifi
#  - influxdb
