registry: harbor.sc.garagen/yggdrasil

applicationRepo: https://github.com/distributed-technologies/application-env-test.git
applicationTargetRevision: 'development'

applications: 
  - ingress
#  - cert-manager
#  - cert-manager-issuer 
#  - argowf
#  - argo-events
#  - harbor
#  - vault
  - prometheus
#  - thanos
  - grafana
#  - loki
#  - jaeger-operator
  - rook
  - ceph
  - loadbalancer
#  - cache
#  - kafka
#  - nifi
#  - influxdb
