ingressDomain: dev2.eloprindelse.dk

#clusterNetworking:
#  ipRangeStart: 192.168.1.40
  # ipRangeStop is both the ipRangeStop but also the ingress loadBalancerIP
#  ipRangeStop: 192.168.1.49


applications: 
  argowf:                 false
  argo-events:            false
  cache:                  false
  ceph:                   false
  cert-manager:           false
  example-guestbook:      false
  grafana:                true
  harbor:                 false
  influxdb:               false
  ingress:                true
  jaeger-operator:        true
  kafka:                  true
  loadbalancer:           false
  loki:                   true
  nifi:                   false
  prometheus:             true
  rook:                   false
  thanos:                 true
  vault:                  false
