applications:
  argowf:                 false
  argo-events:            false
  cache:                  false
  ceph:                   false
  cert-manager:           false
  example-guestbook:      false
  grafana:                true
  harbor:                 false
  influxdb:               false
  ingress:                true
  jaeger-operator:        true
  kafka:                  false
  loadbalancer:           true
  loki:                   true
  nifi:                   false
  prometheus:             true
  rook:                   false
  thanos:                 false
  vault:                  false
  ett-kafka:              true
  ett-postgresql:         true
  ett-auth:               true
  ett-emissions:          false
  ett-measurements:       true
  ett-meteringpoints:     true
  ett-technologies:       true
  ett-datahub2:           true
