#ingressDomain: dev.garagen

#clusterNetworking: 
#  ipRangeStart: 192.168.1.40
  # ipRangeStop is both the ipRangeStop but also the ingress loadBalancerIP
#  ipRangeStop: 192.168.1.49

registry: harbor.sc.garagen/yggdrasil

applications: 
  argowf:                 false
  argo-events:            false
  cache:                  false
  ceph:                   false
  cert-manager:           false
  cert-manager-issuer:    false
  example-guestbook:      false
  grafana:                false
  harbor:                 false
  influxdb:               false
  ingress:                false
  jaeger-operator:        false
  kafka:                  false
  loadbalancer:           false
  loki:                   false
  nifi:                   false
  prometheus:             false
  rook:                   false
  thanos:                 false
  vault:                  false
