---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: 'External applications repo'
  sourceRepos:
    - '*'
  destinations:
    - namespace:  '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: {{ .Values.applicationRepo }}
    targetRevision: {{ .Values.applicationTargetRevision }}
    path: chart
    helm:
      version: v3
      values: |
        installNidhogg: false
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
