{{- $root := . -}}
{{- range $path, $_ := .Files.Glob "**/**/config.yaml" }}
  {{ $project := $root.Files.Get $path | fromYaml }}
  {{- range $project.apps }}
    {{- if has .name $root.Values.applications -}}
      {{- if .ingress }}
      {{- $name := .name }}
        {{- range .ingress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ lower (printf "%s.%s" $name (randAlphaNum 5)) }}
  namespace: {{ $project.namespace }}
  {{- with .annotation }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: "ingress-traefik"
  rules:
    - host: {{if $root.Values.ingressDomain }} {{ printf "%s.%s" .subDomain $root.Values.ingressDomain | quote }} {{ else }} {{ $root.Values.host }} {{ end }}
      http:
        paths:
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
    {{ end }}
    {{ end }} 
  {{ end }}
  {{ end }}
{{ end }}
