{{- $root := . -}}
{{- range $path, $_ := .Files.Glob "**/**/config.yaml" }}
  {{ $project := $root.Files.Get $path | fromYaml }}
  {{ $createAppProject := 0 }}
  {{- range $project.apps }}
    {{- if has .name $root.Values.applications -}}
      {{- $createAppProject = 1 -}}
    {{- end -}}
  {{ end }}
  {{ if $createAppProject }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $project.project.name }}
  namespace: {{ $root.Release.Namespace }}
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: {{ $project.description }}

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  {{- if $project.project.sourceRepos }}
    {{- range $project.project.sourceRepos }}
    - {{ . | quote }}
    {{- end }}
  {{- else }}
    - '*'
  {{- end }}

  destinations:
    - namespace:  {{ $project.namespace | quote }}
      server: {{ $project.project.server }}
  {{- if $project.project.destinations }}
    {{- range $project.project.destinations }}
    - namespace: {{ .namespace | quote }}
      server: {{ .server }}
    {{- end }}
  {{- end }}
    {{- end }}
{{- end }}
