name: rook-ceph
namespace: rook-ceph
namespaceLabels:
  space: service
space: service
description: Rook.

apps:
  - name: rook
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.3
      path: charts/rook/chart
      valuesFile: "rook.yaml"
  - name: ceph
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.6
      path: charts/ceph/chart
      valuesFile: "ceph.yaml"
  - name: ntp
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.2
      path: charts/ntp/chart
      valuesFile: "ntp.yaml"
