name: kafka
clusterService: true
namespace: kafka
description: Kafka.

project:
  name: kafka
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: kafka
    source:
      repoURL: "https://github.com/distributed-technologies/services-kafka.git"
      targetRevision: kafka-dashboard
      path: chart
      valuesFile: "kafka.yaml"
