name: kafka
namespace: kafka
namespaceLabels:
  space: service
space: service
description: Kafka.

apps:
  - name: kafka
    replace: true
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.2.2
      path: charts/kafka/chart
      valuesFile: "kafka.yaml"
