name: eo-kafka
namespace: eo-kafka
description: EnergyOrigin


project:
  name: eo-kafka
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  destinations: 
    - namespace: kube-system
      server: https://kubernetes.default.svc
apps:
  - name: eo-kafka
    source:
      repoURL: "https://github.com/energinet-datahub/eo-kafka.git"
      targetRevision: main
      path: chart
      valuesFile: "eo-kafka.yaml"
