# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'CD apply'
description: 'CD apply'

inputs:
  ENV_FOLDER:
    description: The folder containing the environment files.
    required: true
  ENV_INSTANCE:
    description: The instance for the deployment.
    required: false

  # Azure secrets
  AZURE_TENANT_ID:
    description: The tenant-id for the Azure account.
    required: true
  AZURE_SUBSCRIPTION_ID:
    description: The azure subscription ID.
    required: true
  AZURE_SPN_ID:
    description: The Service Principal ID.
    required: true
  AZURE_SPN_SECRET:
    description: The Service Principal secret.
    required: true

runs:
  using: composite
  steps:
    - name: Load default env variables
      shell: bash
      run: |
        echo "TERRAFORM_BACKEND_AZURE_FILE_PATH=./infrastructure/azure/backend.tf" >> $GITHUB_ENV
        echo "TERRAFORM_BACKEND_HELM_FILE_PATH=./infrastructure/helm/backend.tf" >> $GITHUB_ENV
        echo "TERRAFORM_WORKING_DIR_AZURE_PATH=./infrastructure/azure" >> $GITHUB_ENV
        echo "TERRAFORM_WORKING_DIR_HELM_PATH=./infrastructure/helm" >> $GITHUB_ENV
        echo "TERRAFORM_VERSION==1.0.8" >> $GITHUB_ENV

    - name: Load env variables from file
      shell: bash
      run: |
        cat env/${{ inputs.ENV_FOLDER }}/workflow.env >> $GITHUB_ENV

    - name: Override instance name if Dev branch
      if: inputs.ENV_INSTANCE != ''
      shell: bash
      run: |
        echo "ENVIRONMENT_INSTANCE=${{ inputs.ENV_INSTANCE }}" >> $GITHUB_ENV

    - name: Set generated env variables
      shell: bash
      run: |
        echo "AZURE_TERRAFORM_STATE_RG_NAME=rg-${{ env.PROJECT_NAME }}-tfstate-${{ env.ENVIRONMENT_SHORT }}-${{ env.ENVIRONMENT_INSTANCE }}" >> $GITHUB_ENV
        echo "AZURE_RG_NAME=rg-${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT_SHORT }}-${{ env.ENVIRONMENT_INSTANCE }}" >> $GITHUB_ENV
        echo "TF_VAR_target_revision=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "TF_VAR_environment_folder=${{ inputs.ENV_FOLDER }}" >> $GITHUB_ENV

    - name: Terraform CD Azure
      uses: Energinet-DataHub/.github/.github/actions/terraform-apply@8f5b1b08392de65bdff19ec719f8413b5772eb79
      with:
        PROJECT_NAME: ${{ env.PROJECT_NAME }}
        SERVICE_NAME: ${{ env.SERVICE_NAME }}
        ENVIRONMENT_INSTANCE: ${{ env.ENVIRONMENT_INSTANCE }}
        ENVIRONMENT_SHORT: ${{ env.ENVIRONMENT_SHORT }}
        AZURE_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
        AZURE_SPN_ID: ${{ inputs.AZURE_SPN_ID }}
        AZURE_SPN_SECRET: ${{ inputs.AZURE_SPN_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        AZURE_RG_NAME: ${{ env.AZURE_RG_NAME }}
        TERRAFORM_VERSION: ${{ env.TERRAFORM_VERSION }}
        TERRAFORM_STATE_RG_NAME: ${{ env.AZURE_TERRAFORM_STATE_RG_NAME }}
        # Step specific parameters:
        TERRAFORM_BACKEND_FILE_PATH: ${{ env.TERRAFORM_BACKEND_AZURE_FILE_PATH }}
        TERRAFORM_WORKING_DIR_PATH: ${{ env.TERRAFORM_WORKING_DIR_AZURE_PATH }}

    - name: Terraform CD Helm
      uses: Energinet-DataHub/.github/.github/actions/terraform-apply@8f5b1b08392de65bdff19ec719f8413b5772eb79
      with:
        PROJECT_NAME: ${{ env.PROJECT_NAME }}
        SERVICE_NAME: ${{ env.SERVICE_NAME }}
        ENVIRONMENT_INSTANCE: ${{ env.ENVIRONMENT_INSTANCE }}
        ENVIRONMENT_SHORT: ${{ env.ENVIRONMENT_SHORT }}
        AZURE_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
        AZURE_SPN_ID: ${{ inputs.AZURE_SPN_ID }}
        AZURE_SPN_SECRET: ${{ inputs.AZURE_SPN_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        AZURE_RG_NAME: ${{ env.AZURE_RG_NAME }}
        TERRAFORM_VERSION: ${{ env.TERRAFORM_VERSION }}
        TERRAFORM_STATE_RG_NAME: ${{ env.AZURE_TERRAFORM_STATE_RG_NAME }}
        # Step specific parameters:
        TERRAFORM_BACKEND_FILE_PATH: ${{ env.TERRAFORM_BACKEND_HELM_FILE_PATH }}
        TERRAFORM_WORKING_DIR_PATH: ${{ env.TERRAFORM_WORKING_DIR_HELM_PATH }}
