name: secrets
namespace: secrets
namespaceLabels:
  space: service
space: service
description: Secret services SealedSecrets

apps:
  - name: sealed-secrets
    source:
      repoURL: "https://github.com/bitnami-labs/sealed-secrets/"
      targetRevision: 'v0.17.0'
      chart: helm/sealed-secrets
      valuesFile: "sealed-secrets.yaml"
