name: secrets
namespace: secrets
namespaceLabels:
  space: service
space: service
description: Secret services SealedSecrets

apps:
  - name: sealed-secrets
    source:
      repoURL: 'https://github.com/distributed-technologies/helm-charts'
      targetRevision: 'feature/sealed-secrets'
      path: charts/sealed-secrets/chart
      valuesFile: "sealed-secrets.yaml"
