name: dlr
clusterService: false
namespace: dlr
description: dlr algorithm.

project:
  name: dlr
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*' 
  

apps:
  - name: kafka-scada-event-source
    source:
      repoURL: "https://github.com/distributed-technologies/application-kafka-scada-event-source.git"
      targetRevision: HEAD
      path: chart
      valuesFile: "kafka-scada-event-source.yaml"
