name: registry
clusterService: true
namespace: registry
description: Private Docker registry.

project:
  name: registry
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: registry
    source:
      repoURL: "https://github.com/twuni/docker-registry.helm.git"
      targetRevision: HEAD
      path: .
      valuesFile: "registry.yaml"
